#!/bin/sh

LOGFILE='build.log'

# Build cmd
cargo_build() { RUSTFLAGS="-C link-args=-s" cargo build --release $@ > "$LOGFILE" 2>&1; }

# Remove old
rm -rf 'target/release'

# Either build for default, else build for supplied target
if [ ! -z "$1" ]; then
    echo "Building for target "${1}"... (see "${LOGFILE}" for output)"
    cargo_build --target="$1"
else
    echo "Building for default target... (see "${LOGFILE}" for output)"
    cargo_build
fi

# Print on fail, return exit code
result=$?
[ $result -ne 0 ] && echo 'BUILD FAILED!'
exit $result