[package]
name = "afwm"
version = "0.1.4"
authors = ["kim (grufwub) <grufwub@gmail.com>"]
edition = "2018"

[profile.release]
panic = "abort"

[[bin]]
name = "afwm"

[dependencies]
signal-hook = "0.1"
xcb = "0.9"
xcb-util = { version = "0.3", features = [ "keysyms", "cursor" ]}
x11 = "2.18"